### ISSUE TITLE
Highlight `def` and `class` keywords.

### ISSUE THREAD

**Issue by carlsmith** [zhanzhenzhen/atom-4-color#1]
It seems odd that `def` and `class` aren't highlighted like the other keywords. Still, thanks for this. It's a really useable theme.

It'd probably be nicer if the `@decorator` calls were highlighted yellow too. This is all subjective obviously.

**Comment by zhanzhenzhen** [comment]
Just resolved. Since some old Atom APIs has been deprecated, I used the latest API, so if you upgrade it make sure you upgrade Atom first.

I guess you are writing Python? This issue is because `def` and `class` are treated as not keywords (very weird) in Atom. The only thing I could do is to workaround this issue. I created 2 related issues in their repositories:
https://github.com/atom/language-coffee-script/issues/33
https://github.com/atom/language-javascript/issues/47
